version: "2.3"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq/sheka
    ports:
      - 15672:15672
      - 5672:5672